In [3]:
import pandas as pd
import numpy as np
import nltk

In [4]:
df=pd.read_csv(r"C:\Users\Nikhi\Desktop\Files\Resume\Resume\Final_Resume.csv")
df.columns 


Index(['Category', 'Resume'], dtype='object')

In [5]:
df['Category'].value_counts(dropna=True)
df.shape

(2316, 2)

In [6]:
def listToString(s): 
    
    # initialize an empty string
    str1 = "" 
    
    # traverse in the string  
    for ele in s: 
        str1 = str1+" "+ele  
    
    # return string  
    return str1 

In [7]:
df.head()
list1=df['Category'].value_counts().index
print(list1)

Index(['HR', 'Business Development', 'INFORMATION-TECHNOLOGY', 'FITNESS',
       'SALES', 'ADVOCATE', 'CONSULTANT', 'HEALTHCARE', 'DESIGNER', 'TEACHER',
       'DIGITAL-MEDIA', 'Java Developer', 'Testing', 'AGRICULTURE',
       'DevOps Engineer', 'Python Developer', 'Web Designing', 'Hadoop',
       'Data Science', 'Operations Manager', 'ETL Developer', 'Sales',
       'Blockchain', 'Mechanical Engineer', 'Arts', 'AUTOMOBILE', 'Database',
       'PMO', 'Health and fitness', 'Electrical Engineering',
       'Business Analyst', 'DotNet Developer', 'Automation Testing',
       'Network Security Engineer', 'SAP Developer', 'Civil Engineer', 'BPO',
       'Advocate', 'CHEF'],
      dtype='object')


In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
df['target'] = labelencoder.fit_transform(df['Category'])

In [7]:
df['target'].value_counts().sort_index()
y=df[['target']]
X=df[['Resume']]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.3,random_state=13)

In [9]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1621, 1)
(1621, 1)
(695, 1)
(695, 1)


In [10]:
#Transforming the data into training data 
#Tokenize the collection 
token_list=[]
for i in X_train['Resume']:
    token_list.append(nltk.word_tokenize(i))
#print(len(token_list))
#Lammetize the words 
lammetize_list=[]
for i in token_list:
    lemmatizer=nltk.stem.WordNetLemmatizer()
    lemmatized_token=[lemmatizer.lemmatize(token) for token in i]
    lammetize_list.append(lemmatized_token)
#Remove stop words
from nltk.corpus import stopwords
stop_list=[]
for i in lammetize_list:
    stop_words_removed = [token for token in i if not token in stopwords.words('english') if token.isalpha()]
    stop_list.append(stop_words_removed)


In [11]:
final_list=[]
for i in stop_list:
    sentence_list=listToString(i)
    final_list.append(sentence_list)
#TFIDF min_df=3 and include 2-gram 
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(min_df=5)
v1=vectorizer.fit(final_list)
v2=vectorizer.transform(final_list)
print(len(v1.vocabulary_.keys()))
X_train=pd.DataFrame(v2.toarray(),columns=v1.vocabulary_.keys())
X_train.head()

7807


sales  director  summary  to  continue  career  organization  utilize  \
0      0         0        0   0         0       0             0        0   
1      0         0        0   0         0       0             0        0   
2      0         0        0   0         0       0             0        0   
3      0         0        0   0         0       0             0        0   
4      0         0        0   0         0       0             0        0   

   management  supervision  ...  detroit  pathways  italy  suffolk  releasing  \
0           0            2  ...        0         0      0        0          0   
1           0            1  ...        0         0      0        0          0   
2           0            6  ...        0         0      0        0          0   
3           0            0  ...        0         0      0        0          0   
4           0            0  ...        0         0      0        0          0   

   conferences  slow  offset  compression  ims  
0            0     0       0            0    0  
1            0     0       0            0    0  
2            0     0       0            0    0  
3            0     0       0            0    0  
4            0     0       0            0    0  

[5 rows x 7807 columns]

## Preprocessing Done 

### Validation Data 

In [12]:
#Transforming the data into training data 
#Tokenize the collection 
token_list_test=[]
for i in X_test['Resume']:
    token_list_test.append(nltk.word_tokenize(i))
#print(len(token_list))
#Lammetize the words 
lammetize_list_test=[]
for i in token_list_test:
    lemmatizer=nltk.stem.WordNetLemmatizer()
    lemmatized_token=[lemmatizer.lemmatize(token) for token in i]
    lammetize_list_test.append(lemmatized_token)
#Remove stop words
from nltk.corpus import stopwords
stop_list_test=[]
for i in lammetize_list_test:
    stop_words_removed = [token for token in i if not token in stopwords.words('english') if token.isalpha()]
    stop_list_test.append(stop_words_removed)


In [13]:
final_list_test=[]
for i in stop_list_test:
    sentence_list=listToString(i)
    final_list_test.append(sentence_list)
#Changing it w.r.t Tfidf vector 
v_test=vectorizer.transform(final_list_test)
X_test=pd.DataFrame(v_test.toarray(),columns=v1.vocabulary_.keys())
X_test.head()

sales  director  summary  to  continue  career  organization  utilize  \
0      0         0        0   0         0       0             0        0   
1      0         0        0   0         0       0             0        0   
2      0         0        0   0         0       0             0        0   
3      0         0        0   0         0       0             0        0   
4      0         0        0   0         0       0             0        0   

   management  supervision  ...  detroit  pathways  italy  suffolk  releasing  \
0           0            0  ...        0         0      0        0          0   
1           0            0  ...        0         0      0        0          0   
2           0            1  ...        0         0      0        0          0   
3           0            0  ...        0         0      0        0          2   
4           0            0  ...        0         0      0        0          0   

   conferences  slow  offset  compression  ims  
0            0     0       0            0    0  
1            0     0       0            0    0  
2            0     0       0            0    0  
3            0     0       0            0    0  
4            0     0       0            0    0  

[5 rows x 7807 columns]

### Model Development 

### Naive Bayes

In [14]:
from sklearn.metrics import accuracy_score
## Naive Bayes
from sklearn.naive_bayes import MultinomialNB
NBmodel = MultinomialNB()
# training
NBmodel.fit(X_train, Y_train)
y_pred_NB = NBmodel.predict(X_test)
# evaluation
acc_NB = accuracy_score(Y_test, y_pred_NB)
print("Naive Bayes model Accuracy:: {:.4f}%".format(acc_NB*100))
y_pred_prob_nb = NBmodel.predict_proba(X_test)
print(y_pred_prob_nb[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


Naive Bayes model Accuracy:: 73.0935%
[1.32580623e-307 3.38906335e-291 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 5.55006580e-314 0.00000000e+000 1.32690926e-028
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 1.14563799e-262 2.85138094e-287
 0.00000000e+000 0.00000000e+000 1.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000]


### Logistic Regression

In [15]:
from sklearn.linear_model import LogisticRegression
Logitmodel = LogisticRegression()
# training
Logitmodel.fit(X_train, Y_train)
y_pred_logit = Logitmodel.predict(X_test)
# evaluation
from sklearn.metrics import accuracy_score
acc_logit = accuracy_score(Y_test, y_pred_logit)
print("Logit model Accuracy:: {:.4f}%".format(acc_logit*100))
y_pred_prob_logit = Logitmodel.predict_proba(X_test)
print(y_pred_prob_logit[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logit model Accuracy:: 81.5827%
[2.02966083e-08 2.48987626e-04 1.93609997e-09 1.63625885e-19
 1.06769905e-16 2.35295096e-13 2.84037788e-06 2.82232037e-14
 4.84395837e-05 1.63278701e-08 3.14015555e-11 9.46659918e-01
 2.61119756e-14 1.48045686e-07 7.55449725e-08 4.64359021e-18
 3.05007894e-09 3.18350537e-11 7.41729162e-13 3.32649793e-12
 6.62577922e-13 6.68634040e-10 8.71603799e-06 1.51786479e-15
 3.62961028e-12 2.43506140e-14 5.30295553e-02 3.65526528e-12
 4.22709418e-14 1.77697313e-08 8.12346996e-08 9.20978756e-07
 1.59910931e-13 3.57081438e-11 2.57455398e-07 2.84003884e-13
 2.37571320e-11 5.09540617e-14 1.49454159e-11]


### Decision Tree

In [16]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.metrics import accuracy_score
DTmodel = DecisionTreeClassifier(min_samples_leaf=15,random_state=0) ## number of trees and number of layers/depth
#training
DTmodel.fit(X_train, Y_train)
y_pred_DT = DTmodel.predict(X_test)
#evaluation
acc_DT = accuracy_score(Y_test, y_pred_DT)
print("Decision Tree Model Accuracy: {:.4f}%".format(acc_DT*100))
y_pred_prob_dt = DTmodel.predict_proba(X_test)
print(y_pred_prob_dt[0])

Decision Tree Model Accuracy: 74.8201%
[0.         0.         0.04166667 0.         0.         0.
 0.04166667 0.         0.         0.04166667 0.         0.125
 0.         0.         0.04166667 0.         0.         0.04166667
 0.         0.         0.         0.04166667 0.         0.5
 0.         0.         0.04166667 0.         0.         0.
 0.         0.         0.         0.         0.08333333 0.
 0.         0.         0.        ]


### Random Forest Classifier 

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
RFmodel = RandomForestClassifier(n_estimators=100, max_depth=15, bootstrap=True, random_state=0) ## number of trees and number of layers/depth
#training
RFmodel.fit(X_train, Y_train)
y_pred_RF = RFmodel.predict(X_test)
#evaluation
acc_RF = accuracy_score(Y_test, y_pred_RF)
print("Random Forest Model Accuracy: {:.4f}%".format(acc_RF*100))
y_pred_prob_rf = RFmodel.predict_proba(X_test)
print(y_pred_prob_rf)

<ipython-input-17-4ce8e5bd9cf5>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  RFmodel.fit(X_train, Y_train)


Random Forest Model Accuracy: 80.2878%
[[0.06816427 0.04234525 0.03540047 ... 0.01023758 0.00093585 0.00074334]
 [0.00136254 0.00275336 0.00148906 ... 0.00153413 0.0154043  0.01927051]
 [0.0087725  0.00719537 0.00302789 ... 0.00333481 0.00434275 0.00466574]
 ...
 [0.05731961 0.05434153 0.02240192 ... 0.02710776 0.00172684 0.00154733]
 [0.0806935  0.05623166 0.03078309 ... 0.04830809 0.00393529 0.00291041]
 [0.01091068 0.00903587 0.00321523 ... 0.00758478 0.02297237 0.00593032]]


### Xgboost Classifier 

In [18]:
from xgboost import XGBClassifier
xgmodel = XGBClassifier(random_state=0) ## number of trees and number of layers/depth
#training
xgmodel.fit(X_train, Y_train)
y_pred_xg = xgmodel.predict(X_test)
#evaluation
acc_xg = accuracy_score(Y_test, y_pred_xg)
print("Xgboost Classifier Model Accuracy: {:.4f}%".format(acc_xg*100))
y_pred_prob_xg = xgmodel.predict_proba(X_test)
print(y_pred_prob_xg[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


[19:17:13] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.0/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Xgboost Classifier Model Accuracy: 86.1871%
[0.2436162  0.03113217 0.02810878 0.00196076 0.00141979 0.00232898
 0.02665592 0.00226366 0.00701143 0.01136157 0.00234535 0.01307111
 0.00228667 0.00442105 0.06212335 0.00266147 0.00519187 0.00253212
 0.00239003 0.00210587 0.00196536 0.01101076 0.00423547 0.14767592
 0.00389324 0.00312817 0.23004098 0.00310099 0.00209633 0.00552354
 0.00255676 0.11422241 0.00496793 0.00118082 0.00172513 0.0021735
 0.00113951 0.00195521 0.00241974]


### Light GBM Classifier 

In [19]:
import lightgbm as lgb
lgbmodel = lgb.LGBMClassifier(learning_rate=0.09,max_depth=-5,random_state=0) ## number of trees and number of layers/depth
#training
lgbmodel.fit(X_train, Y_train, verbose=20,eval_metric='logloss')
y_pred_lgb = lgbmodel.predict(X_test)
#evaluation
acc_lgb = accuracy_score(Y_test, y_pred_lgb)
print("Light GMB Classifier Model Accuracy: {:.4f}%".format(acc_lgb*100))
y_pred_prob_lgb = lgbmodel.predict_proba(X_test)
print(y_pred_prob_lgb[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Nikhi\anaconda3\lib\site-packages\lightgbm\sklearn.py:736: UserWarning: 'verbose' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose' argument is deprecated and will be removed in a future release of LightGBM. "


Light GMB Classifier Model Accuracy: 86.0432%
[2.52290580e-01 1.38031376e-02 5.20346734e-04 2.02369727e-04
 2.24885367e-04 3.31447187e-04 9.10450498e-03 5.29007815e-04
 5.93300317e-04 3.95645482e-02 3.91966590e-04 2.75075256e-03
 1.39726921e-04 5.21686549e-04 2.84968309e-03 2.41360026e-04
 2.93979749e-04 4.38895726e-04 7.68008484e-04 4.25913852e-04
 2.66335817e-04 5.70501532e-04 7.43801152e-04 1.09031416e-01
 4.85335187e-04 2.17710962e-04 5.57851260e-01 3.48794337e-04
 3.61479942e-04 3.60284904e-04 3.33924755e-04 6.86851767e-04
 5.54564017e-04 1.80943502e-04 3.26079414e-04 2.70149664e-04
 6.26000163e-04 5.14594930e-04 2.83870251e-04]


### CAT Boost Classifier 

In [20]:
from catboost import CatBoostClassifier
catmodel = CatBoostClassifier(random_state=0) ## number of trees and number of layers/depth
#training
catmodel.fit(X_train, Y_train, verbose=20)
y_pred_cat = catmodel.predict(X_test)
#evaluation
acc_cat = accuracy_score(Y_test, y_pred_cat)
print("Light GMB Classifier Model Accuracy: {:.4f}%".format(acc_cat*100))
y_pred_prob_cat = catmodel.predict_proba(X_test)
print(y_pred_prob_cat[0])

Learning rate set to 0.0811
0:	learn: 3.4972329	total: 2.57s	remaining: 42m 48s
20:	learn: 2.1377269	total: 49.2s	remaining: 38m 13s
40:	learn: 1.6613278	total: 1m 33s	remaining: 36m 37s
60:	learn: 1.3326875	total: 2m 16s	remaining: 34m 55s
80:	learn: 1.0992294	total: 2m 56s	remaining: 33m 24s
100:	learn: 0.8762778	total: 3m 36s	remaining: 32m 8s
120:	learn: 0.7330978	total: 4m 16s	remaining: 31m 4s
140:	learn: 0.6359206	total: 4m 56s	remaining: 30m 7s
160:	learn: 0.5839990	total: 5m 43s	remaining: 29m 48s
180:	learn: 0.5461974	total: 6m 32s	remaining: 29m 47s
200:	learn: 0.5167014	total: 7m 13s	remaining: 28m 51s
220:	learn: 0.4966811	total: 7m 53s	remaining: 27m 57s
240:	learn: 0.4752953	total: 9m 2s	remaining: 28m 36s
260:	learn: 0.4633232	total: 10m 25s	remaining: 29m 38s
280:	learn: 0.4502862	total: 11m 49s	remaining: 30m 22s
300:	learn: 0.4411907	total: 13m 12s	remaining: 30m 47s
320:	learn: 0.4332368	total: 13m 53s	remaining: 29m 34s
340:	learn: 0.4242250	total: 14m 32s	remainin

### ANN

In [43]:
## Neural Network and Deep Learning
from sklearn.neural_network import MLPClassifier
DLmodel = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(150,1200), random_state=1)
# training
DLmodel.fit(X_train, Y_train)
y_pred_DL= DLmodel.predict(X_test)
# evaluation
acc_DL = accuracy_score(Y_test, y_pred_DL)
print("DL model Accuracy: {:.4f}%".format(acc_DL*100))
y_pred_prob_dl = DLmodel.predict_proba(X_test)
print(y_pred_prob_dl[0])

C:\Users\Nikhi\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


DL model Accuracy: 76.8345%
[5.80817188e-139 1.28897246e-074 8.54757161e-128 0.00000000e+000
 0.00000000e+000 0.00000000e+000 1.16039238e-114 0.00000000e+000
 0.00000000e+000 8.19966845e-108 1.38230556e-162 1.00000000e+000
 0.00000000e+000 4.77226643e-071 7.11087973e-148 3.11482784e-313
 3.02991762e-311 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 1.53670550e-230 2.31255730e-111 0.00000000e+000
 0.00000000e+000 0.00000000e+000 1.43345593e-089 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 4.41502547e-129 0.00000000e+000 0.00000000e+000
 8.45091652e-218 0.00000000e+000 0.00000000e+000]


### LSTM 

In [9]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
docs_x=df['Resume']
docs_c=df['Category']

In [10]:
# define vocab
from collections import Counter
words = [j for i in docs_x for j in i]
count_words = Counter(words)
total_words = len(words)
sorted_words = count_words.most_common(total_words)
vocab_to_int = {w: i+1 for i, (w,c) in enumerate(sorted_words)} # note 0 is for null
# one hot
text_int = [] 
for i in docs_x:
    r = [vocab_to_int[w] for w in i]
    text_int.append(r)
# dummy label
encoded_labels = [1 if label =='subj' else 0 for label in docs_c]

In [12]:
from sklearn.model_selection import train_test_split
X_train_lstm,X_test_lstm,Y_train_lstm,Y_test_lstm=train_test_split(text_int,encoded_labels,test_size=0.3,random_state=13)
y_train = np.array(Y_train_lstm)
y_test = np.array(Y_test_lstm)
x_train = np.array(X_train_lstm)
x_test = np.array(X_test_lstm)

<ipython-input-12-c258fcd0233e>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_train = np.array(X_train_lstm)
<ipython-input-12-c258fcd0233e>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x_test = np.array(X_test_lstm)


In [15]:
# build model
import keras
from keras.preprocessing import sequence 
from keras.models import Sequential 
from keras.layers import Dense, Embedding, Flatten
from keras.layers import LSTM
from keras.layers import Dense, Dropout
max_features = total_words
maxlen = 200
batch_size = 100
# padding
x_train = sequence.pad_sequences(x_train, maxlen=maxlen)
x_test = sequence.pad_sequences(x_test, maxlen=maxlen)
# model architecture
model = Sequential()
model.add(Embedding(max_features, 20, input_length=maxlen))
model.add(LSTM(40, dropout=0.20, recurrent_dropout=0.20))
model.add(Dropout(0.1))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, batch_size=batch_size, epochs=5, validation_data=(x_test, y_test))

Epoch 1/5
17/17 [==============================] - 48s 2s/step - loss: 0.5968 - accuracy: 0.9661 - val_loss: 0.3015 - val_accuracy: 1.0000
Epoch 2/5
17/17 [==============================] - 40s 2s/step - loss: 0.0680 - accuracy: 1.0000 - val_loss: 0.0065 - val_accuracy: 1.0000
Epoch 3/5
17/17 [==============================] - 39s 2s/step - loss: 0.0047 - accuracy: 1.0000 - val_loss: 0.0027 - val_accuracy: 1.0000
Epoch 4/5
17/17 [==============================] - 38s 2s/step - loss: 0.0025 - accuracy: 1.0000 - val_loss: 0.0017 - val_accuracy: 1.0000
Epoch 5/5
17/17 [==============================] - 39s 2s/step - loss: 0.0018 - accuracy: 1.0000 - val_loss: 0.0013 - val_accuracy: 1.0000


### Craiglist data 

In [65]:
test=pd.read_csv(r"C:\Users\Nikhi\Desktop\Files\Resume\run_results_sfbay.csv",dtype={'selection1_selection2':"category"})
test1['selection1_selection2']=test1['selection1_selection2'].astype('str')

In [71]:
#Tokenize the collection 
token_test=[]
j=0
for i in test1['selection1_selection2']:
    token_test.append(nltk.word_tokenize(i))
#print(len(token_list))
#Lammetize the words 
lammetize_test=[]
for i in token_test:
    lemmatizer=nltk.stem.WordNetLemmatizer()
    lemmatized_token=[lemmatizer.lemmatize(token) for token in i]
    lammetize_test.append(lemmatized_token)
#Remove stop words
from nltk.corpus import stopwords
stop_test=[]
for i in lammetize_test:
    stop_words_removed = [token for token in i if not token in stopwords.words('english') if token.isalpha()]
    stop_test.append(stop_words_removed)
print(len(token_test))

1510


In [72]:
final_test=[]
for i in stop_test:
    sentence_list=listToString(i)
    final_test.append(sentence_list)
#Changing it w.r.t Tfidf vector 
v_test_c=vectorizer.transform(final_test)
test=pd.DataFrame(v_test_c.toarray(),columns=v1.vocabulary_.keys())
test.head()

sales  director  summary  to  continue  career  organization  utilize  \
0      0         0        0   0         0       0             0        0   
1      0         0        0   0         0       0             0        0   
2      0         0        0   0         0       0             0        0   
3      0         0        0   0         0       0             0        0   
4      0         0        0   0         0       0             0        0   

   management  supervision  ...  detroit  pathways  italy  suffolk  releasing  \
0           0            0  ...        0         0      0        0          0   
1           0            0  ...        0         0      0        0          0   
2           0            0  ...        0         0      0        0          0   
3           0            0  ...        0         0      0        0          0   
4           0            0  ...        0         0      0        0          0   

   conferences  slow  offset  compression  ims  
0            0     0       0            0    0  
1            0     0       0            0    0  
2            0     0       0            0    0  
3            0     0       0            0    0  
4            0     0       0            0    0  

[5 rows x 7807 columns]

In [77]:
#Naive Bayes 
y_pred_prob_nb = NBmodel.predict_proba(test)
y_pred_prob_nb=pd.DataFrame(y_pred_prob_nb,columns=list1)
y_pred_prob_nb.to_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\Results\y_pred_prob_nb.csv")


In [78]:
#Logistic Regression 
y_pred_prob_log = Logitmodel.predict_proba(test)
y_pred_prob_log=pd.DataFrame(y_pred_prob_log,columns=list1)
y_pred_prob_log.to_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\Results\y_pred_prob_log.csv")


In [79]:
#Decision Tree
y_pred_prob_dt = DTmodel.predict_proba(test)
y_pred_prob_dt=pd.DataFrame(y_pred_prob_dt,columns=list1)
y_pred_prob_dt.to_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\Results\y_pred_prob_dt.csv")


In [80]:
#Random Forest
y_pred_prob_rf = RFmodel.predict_proba(test)
y_pred_prob_rf=pd.DataFrame(y_pred_prob_rf,columns=list1)
y_pred_prob_rf.to_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\Results\y_pred_prob_rf.csv")

In [81]:
#Xgboost 
y_pred_prob_xg = xgmodel.predict_proba(test)
y_pred_prob_xg=pd.DataFrame(y_pred_prob_xg,columns=list1)
y_pred_prob_xg.to_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\Results\y_pred_prob_xg.csv")

In [82]:
#CAT Boost
y_pred_prob_cat = catmodel.predict_proba(test)
y_pred_prob_cat=pd.DataFrame(y_pred_prob_cat,columns=list1)
y_pred_prob_cat.to_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\Results\y_pred_prob_cat.csv")

In [83]:
#Light GBM
y_pred_prob_lgb = lgbmodel.predict_proba(test)
y_pred_prob_lgb=pd.DataFrame(y_pred_prob_lgb,columns=list1)
y_pred_prob_lgb.to_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\Results\y_pred_prob_lgb.csv")

In [84]:
#ANN DLmodel
y_pred_prob_ann = DLmodel.predict_proba(test)
y_pred_prob_ann=pd.DataFrame(y_pred_prob_ann,columns=list1)
y_pred_prob_ann.to_csv(r"C:\Users\Nikhi\OneDrive - purdue.edu\Mod 2\Analyzing Unstructured Data\Group Project\Results\y_pred_prob_ann.csv")